### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by shadowcaptain21** [runescapejon/BorderProtector#3]
When a player is outside the border they just get spam a message "you cannot bypass  outside the border" thats it they didnt get teleported back to spawn nor /rtp

**Comment by runescapejon** [comment]
This is a bug on Sponge end https://github.com/SpongePowered/SpongeCommon/issues/2257
there is an alternative to use, you can use Nucleus RTP system. Also be sure to properly configure it

**Comment by shadowcaptain21** [comment]
well can u add a kill command instead?

**Comment by runescapejon** [comment]
Once your outside of the border it kill tried you regardless. So, it's redundant to add this. That being said you there are bypass to this idea things like having god mode or some sort of armor that block it. That why this alternative using RTP system from nucleus is best for now until the sponge team develop their fixes to the bug.

**Comment by runescapejon** [comment]
Fixed in sponge end. Closing this
